import { Layout } from "antd";
import Head from "next/head";
import { Col, Row } from "antd";
import FeedComponent from "@/components/FeedComponent";

const { Content } = Layout;

export default function Home() {
  return (
    <>
      <Head>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content className="d-flex justify-content-center">
        <div className="container-fluid maxWidth">
          <Row justify={"center"}>
            <Col span={24}>
              <FeedComponent />
            </Col>
          </Row>
        </div>
      </Content>
    </>
  );
}
